### ISSUE TITLE
stop anim会在最后一帧之前调用

### ISSUE THREAD

**Issue by nickeyfff** [yuyashuai/SilkyAnimation#16]
会导致sleep的时候, 这个线程被杀,然后报异常

W/System.err: java.lang.InterruptedException
W/System.err:     at java.lang.Thread.sleep(Native Method)
                  at java.lang.Thread.sleep(Thread.java:1031)
                  at java.lang.Thread.sleep(Thread.java:985)
                  at com.yuyashuai.silkyanimation.SilkyAnimation$MyCallBack$1.run(SilkyAnimation.java:822)

**Comment by yuyashuai** [comment]
是的，这个问题存在，修改控制位后并没有手动在线程中停止，接下来会改掉，谢谢！
