### ISSUE TITLE
使用sd卡片中的图片播放，解析文件过程中出现死循环？

### ISSUE THREAD

**Issue by sxdwzxcsw** [yuyashuai/SilkyAnimation#43]
调用方法animationView1.playAnimationFromFile(“/storage/emulated/0/testimage/image1/”);
然后就报下面错误了。

07-30 13:45:16.031 2430-2430/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.**.test, PID: 2430
    java.lang.StackOverflowError: stack size 8MB
        at com.yuyashuai.frameanimation.FrameAnimationUtil.getPathList(FrameAnimationUtil.kt)
        at com.yuyashuai.frameanimation.FrameAnimationUtil.getPathList(FrameAnimationUtil.kt:76)
        at com.yuyashuai.frameanimation.FrameAnimationUtil.getPathList(FrameAnimationUtil.kt:76)
        at com.yuyashuai.frameanimation.FrameAnimationUtil.getPathList(FrameAnimationUtil.kt:76)
        at com.yuyashuai.frameanimation.FrameAnimationUtil.getPathList(FrameAnimationUtil.kt:76)

**Comment by futureLix** [comment]
![image](https://user-images.githubusercontent.com/24717662/104809758-66b5e700-582a-11eb-8769-6c9f872c189c.png)
好像是这个方法，你注释掉这个方法之后再试一下
